# Generated by Django 5.1.3 on 2024-11-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_class_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimeslot',
            name='class_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.class'),
            preserve_default=False,
        ),
    ]
